### ISSUE TITLE
Selector on watches.yaml not honoured 

### ISSUE THREAD

**Issue by anupchandak** [operator-framework/ansible-operator-plugins#31]
To control the scope of an operator in a multi-development environment, I have defined a selector at the `watches.yaml` level by referring [here](https://sdk.operatorframework.io/docs/building-operators/ansible/reference/watches/)

The selector is defined as something like the below (presented below with equivalent dummy values)

```
- version: v1
  group: mytest.com
  kind: MyKind
  snakeCaseParameters: False
  playbook: playbooks/create.yml
  finalizer:
    name: myTest.com/finalizer
    playbook: playbooks/purge.yml
  selector:
    matchExpressions:
      - key: mytest.com/controller-namespace
        operator: In
        values: 
          - "my-test-na"
 ```

When I start my ansible runner then as expected, I see the following log at the start
```
{"level":"info","ts":1676367873.856818,"logger":"cmd","msg":"Watch namespaces not configured by environment variable WATCH_NAMESPACE or file. Watching all namespaces.","Namespace":""}
```
and I expect that my Operator will still not worry (watch) about CR defined with the label `mytest.com/controller-namespace=your-test-na`. But it does and reconciles it. 

It is an ansible based operator and environment details are as below: 
```
% ansible --version
/usr/local/lib/python3.9/site-packages/paramiko/transport.py:236: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,
ansible [core 2.13.5]
  config file = /Users/anupchandak/ansible-profiler.cfg
  configured module search path = ['/Users/anupchandak/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/anupchandak/Library/Python/3.9/lib/python/site-packages/ansible
  ansible collection location = /Users/anupchandak/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.14 (main, Sep  6 2022, 23:29:09) [Clang 13.1.6 (clang-1316.0.21.2.5)]
  jinja version = 3.1.2
  libyaml = True
```
